baseURL: 'https://taakuuyaa.github.io/'
copyright: '© 2018-2025 taakuuyaa'
title: Profile
author: taakuuyaa
pagination:
  pagerSize: 5
languageCode: ja
DefaultContentLanguage: ja
enableInlineShortcodes: true
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "taakuuyaa's Blog"
  author: taakuuyaa
  ShowReadingTime: true
  SetThemeAuto: true
  contentTypeName: posts
  defaultTheme: auto
  ShowShareButtons: false
  
  profileMode:
    enabled: true
    title: "Hello there 👋"
    subtitle: "I'm taakuuyaa, a software engineer."
    imageUrl: '/icon.png'
    imageTitle: icon image
    buttons:
      - name: "Zenn"
        url: "https://zenn.dev/taakuuyaa"
        icon: "zenn"

  socialIcons:
    - name: x
      url: 'https://twitter.com/taakuuyaa_'
    - name: github
      url: 'https://github.com/taakuuyaa'
